---
title: "Group 14 CA pollution burden"
author: "Kat Cotti & Jake Niyri"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

```{r}
#Read in the data as an object 'ces' using here:
ces <- read.csv(here("data", "ces3demographics.csv")) %>% 
  
#Convert column headers to lower snake case:
janitor::clean_names()
```

```{r}
#Create a plot object to view the data

percent_white_plot <- ces %>%
  ggplot(aes(x=white, y=ces_3_0_score))+
  geom_hex() + #Update graph type to 2D hexbin 
  
  #formatting graph with aaalllll the pretties
  scale_fill_gradient(low="darkorchid4", high = "magenta")+  #adjust fill
  labs(x = "White Population Percentage \n (Based on 2010 Census Data) ", y = "CalEnviroScreen Pollution Burden Score \n (CES 3.0 Score)")#+  #label graph with appropriate axis labels
  #theme_minimal()   #this does not in any way adjust the theme to a minimal setting

percent_white_plot
```

